"""Add ContratoItem table

Revision ID: 2908569d81de
Revises: 
Create Date: 2026-01-13 10:06:34.401789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2908569d81de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('item_lpu_id', sa.Integer(), nullable=False),
    sa.Column('valor_venda', sa.Float(), nullable=False),
    sa.Column('valor_repasse', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['item_lpu_id'], ['itens_lpu.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'item_lpu_id', name='uq_contrato_item')
    )
    with op.batch_alter_table('contrato_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contrato_itens_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contrato_itens_item_lpu_id'), ['item_lpu_id'], unique=False)

    op.drop_table('lancamentos')
    with op.batch_alter_table('itens_lpu_preco_historico', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('valor_custo_anterior',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('valor_receita_anterior',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('valor_custo_novo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('valor_receita_novo',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_preco_hist_data'))
        batch_op.drop_index(batch_op.f('idx_preco_hist_item'))
        batch_op.create_index(batch_op.f('ix_itens_lpu_preco_historico_item_lpu_id'), ['item_lpu_id'], unique=False)

    with op.batch_alter_table('solicitacoes_reposicao', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('idx_solicit_status'))
        batch_op.drop_index(batch_op.f('idx_solicit_tecnico'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_stockmov_chamado'))
        batch_op.create_index(batch_op.f('ix_stock_movements_chamado_id'), ['chamado_id'], unique=False)

    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.drop_column('saldo_atual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo_atual', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_chamado_id'))
        batch_op.create_index(batch_op.f('idx_stockmov_chamado'), ['chamado_id'], unique=False)

    with op.batch_alter_table('solicitacoes_reposicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_solicit_tecnico'), ['tecnico_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_solicit_status'), ['status'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('itens_lpu_preco_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_lpu_preco_historico_item_lpu_id'))
        batch_op.create_index(batch_op.f('idx_preco_hist_item'), ['item_lpu_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_preco_hist_data'), ['data_alteracao'], unique=False)
        batch_op.alter_column('valor_receita_novo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_custo_novo',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_receita_anterior',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('valor_custo_anterior',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('lancamentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tecnico_id', sa.INTEGER(), nullable=False),
    sa.Column('pagamento_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), nullable=False),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.Column('chamado_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados.id'], ),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contrato_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contrato_itens_item_lpu_id'))
        batch_op.drop_index(batch_op.f('ix_contrato_itens_cliente_id'))

    op.drop_table('contrato_itens')
    # ### end Alembic commands ###
