"""Add token to tecnico

Revision ID: 4899eb252434
Revises: 9492adf1f914
Create Date: 2025-12-24 10:16:00.401002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4899eb252434'
down_revision = '9492adf1f914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_acesso', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_tecnicos_token_acesso', ['token_acesso'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnicos', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tecnicos_token_acesso', type_='unique')
        batch_op.drop_column('token_acesso')

    # ### end Alembic commands ###
